services:
  - type: web
    name: loder-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_USER
        fromDatabase:
          name: loder-db
          property: user
      - key: DB_HOST
        fromDatabase:
          name: loder-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: loder-db
          property: database
      - key: DB_PASSWORD
        fromDatabase:
          name: loder-db
          property: password
      - key: DB_PORT
        fromDatabase:
          name: loder-db
          property: port

databases:
  - name: loder-db
    databaseName: loder
    user: loder
    plan: free

